const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),box={};vm.createContext(box);vm.runInContext(fs.readFileSync(root+'/apps-script/Core.gs','utf8'),box);const C=box.RevenueCore,seed=JSON.parse(fs.readFileSync(root+'/data/seed.json'));let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name);}const account={id:'A',brand:'Acme',aliases:'แอคมี',customer_type:'PROSPECT',industry:'RETAIL',area:'BANGKOK',contact_email:'client@example.com'};
const docs=Array.from({length:5},(_,i)=>({id:'C'+i,status:'READY',file_name:'file-'+i+'.pdf',kind:['CASE_STUDY','CREDENTIAL','INDUSTRY_OVERVIEW'][i%3],drive_url:'https://drive.google.com/file/d/F'+i+'/view',modified_at:'2026-09-30T01:00:00Z',title_th:'กรณีศึกษา: สื่อใกล้จุดขาย '+i,title_en:'Case study: Near-store media '+i,tags:'RETAIL|LAUNCH|FOOTFALL|EXPANSION',readers:'anyone',summary_th:'มุมมองเกี่ยวกับพฤติกรรมผู้บริโภค',summary_en:'Perspectives on consumer behaviour.'}));
const ctx={now:'2026-09-30',accounts:[account],media:seed.media,credentials:docs,config:seed.config};const trigger={id:'D',account_id:'A',title:'Acme เปิดสาขาใหม่',source_url:'https://example.com/article',publisher:'Source',published_at:'2026-09-30'};
const build=()=>JSON.parse(JSON.stringify(C.build(trigger,ctx)));
test('prospect becomes new opportunity',()=>assert.equal(build().category,'NEW_OPPORTUNITY'));
test('existing becomes upsales',()=>{account.customer_type='EXISTING';assert.equal(build().category,'UPSALES');account.customer_type='PROSPECT';});
test('unknown never assumed existing',()=>{account.customer_type='UNKNOWN';assert.equal(build().category,'NEEDS_CLASSIFICATION');account.customer_type='PROSPECT';});
test('brand outside master is new',()=>assert.equal(C.build({...trigger,account_id:'',brand:'Unmapped',title:'Unmapped launch product'},ctx).category,'NEW_OPPORTUNITY'));
test('ambiguous brand not auto matched',()=>assert.equal(C.detectAccount('Acme and Other launch',[account,{brand:'Other'}]),null));
test('short token not confused with longer words',()=>assert.equal(C.detectAccount('Corn launch',[{brand:'ORX'}]),null));
test('case-insensitive English brand',()=>assert.equal(C.detectAccount('ACME launches',[account]).id,'A'));
test('non-signal held',()=>assert.throws(()=>C.build({...trigger,title:'Acme routine update'},ctx)));
test('credentials capped at three',()=>assert.equal(build().credentials.length,3));
test('complementary knowledge topics chosen',()=>{let d=build();assert.equal(new Set(C.selectedDocs(d,ctx).map(x=>x.title_en)).size,3);});
test('duplicate link not selected twice',()=>assert.equal(C.credentials(build(),[docs[0],{...docs[0],id:'COPY'}]).length,1));
test('unread docs excluded',()=>assert.equal(C.credentials(build(),[{...docs[0],status:'ERROR'}]).length,0));
test('unrelated industry excluded',()=>assert.equal(C.credentials(build(),[{...docs[0],tags:'HOSPITAL|LAUNCH'}]).length,0));
test('unrelated objective excluded',()=>assert.equal(C.credentials(build(),[{...docs[0],tags:'OTT|EVENT'}]).length,0));
test('unsupported link excluded',()=>assert.equal(C.credentials(build(),[{...docs[0],drive_url:'javascript:alert(1)'}]).length,0));
test('knowledge mode does not recommend media',()=>assert.equal(build().media.length,0));
test('no prices or inventory in seed',()=>{assert.ok(!JSON.stringify(seed).includes('monthly_rate'));assert.ok(!('inventory'in seed));});
test('final gate required',()=>assert.ok(C.validate(build(),ctx).errors.some(e=>e.includes('ขั้นสุดท้าย'))));
test('ready after final confirmation',()=>{let d=build();d.review_confirmed=true;assert.equal(C.validate(d,ctx).ok,true);});
test('four documents blocked',()=>{let d=build();d.credentials.push({id:'C4',modified_at:docs[4].modified_at,title_th:docs[4].title_th,title_en:docs[4].title_en});assert.ok(C.validate(d,ctx).errors.some(e=>e.includes('ไม่เกิน 3')));});
test('stale document blocked',()=>{let d=build();d.credentials[0].modified_at='old';assert.ok(C.validate(d,ctx).errors.some(e=>e.includes('เอกสารเปลี่ยน')));});
test('missing document blocked',()=>{let d=build();d.credentials[0].id='missing';assert.equal(C.validate(d,ctx).ok,false);});
test('filename title blocked',()=>{let d=build();d.credentials[0].title_th=docs[0].file_name;assert.ok(C.validate(d,ctx).errors.some(e=>e.includes('ชื่อไฟล์')));});
test('restricted Drive link needs final access check',()=>{let local={...ctx,credentials:docs.map(d=>({...d,readers:''}))},d=build();d.review_confirmed=true;assert.equal(C.validate(d,local).ok,false);d.links_access_confirmed=true;assert.equal(C.validate(d,local).ok,true);});
test('domain access recognized',()=>{let local={...ctx,credentials:docs.map(d=>({...d,readers:'domain:example.com'}))},d=build();d.review_confirmed=true;assert.equal(C.validate(d,local).ok,true);});
test('type changed after review blocks approval',()=>{let d=build();d.review_confirmed=true;account.customer_type='EXISTING';assert.equal(C.validate(d,ctx).ok,false);account.customer_type='PROSPECT';});
test('email recipient injection blocked',()=>{let d=build();d.email_to='a@example.com,b@example.com';assert.equal(C.validate(d,ctx).ok,false);});
test('subject header injection blocked',()=>{let d=build();d.emails.TH.subject='hello\nBcc:x@example.com';assert.equal(C.validate(d,ctx).ok,false);});
test('both official language versions generated',()=>{let d=build();assert.ok(d.emails.TH.body.startsWith('เรียน'));assert.ok(d.emails.EN.body.startsWith('Dear'));assert.ok(d.emails.EN.body.includes(d.title));});
test('business type affects official email',()=>{let d=build();d.industry='HOSPITAL';assert.ok(C.emails(d,ctx).EN.body.includes('healthcare'));});
test('objective affects regenerated email',()=>{let d=build();d.objective='EVENT';assert.ok(C.emails(d,ctx).EN.body.includes('participation'));});
test('upsales outreach differs',()=>{let d=build();d.category='UPSALES';assert.ok(C.emails(d,ctx).EN.body.includes('share research'));});
test('custom solutions retained in regeneration',()=>{let d=build();d.knowledge_note_en='Custom business solution';assert.ok(C.emails(d,ctx).EN.body.includes('Custom business solution'));});
test('HTML uses semantic link labels, not filenames',()=>{let d=build(),html=C.emailOutput(d,ctx).html;assert.ok(html.includes(docs[0].title_th));assert.ok(!html.includes(docs[0].file_name));});
test('English links use English labels',()=>{let d=build();d.language='EN';assert.ok(C.emailOutput(d,ctx).html.includes(docs[0].title_en));});
test('custom emails exported exactly',()=>{let d=build();d.emails.TH.body='CUSTOM';assert.ok(C.emailOutput(d,ctx).html.includes('CUSTOM'));});
test('untrusted source escaped',()=>{let d=build();d.title='<img src=x onerror=alert(1)>';assert.ok(!C.emailOutput(d,ctx).html.includes('<img'));});
test('document title derived from read content, English is English',()=>{let text='Restaurant marketing and out-of-home media near point of sale\nOOH supports food product launches and encourages consumer awareness in relevant locations.';let s=C.describeDoc(text,'CASE_STUDY','Case Study');assert.ok(s.title_th.includes('กรณีศึกษา'));assert.ok(!/[\u0e00-\u0e7f]/.test(s.title_en));});
test('empty OCR not silently treated as read',()=>assert.equal(C.describeDoc('tiny','CREDENTIAL',''),null));
test('stale signal blocked at final review',()=>{let d=build();d.published_at='2026-01-01';assert.equal(C.validate(d,ctx).ok,false);});
const times=[['2026-09-30T01:29:00Z',false],['2026-09-30T01:30:00Z',true],['2026-09-30T10:59:59Z',true],['2026-09-30T11:00:00Z',false],['2026-10-03T01:30:00Z',false],['2026-10-04T05:00:00Z',false],['2026-10-02T10:59:00Z',true],['2026-10-05T01:30:00Z',true]];
times.forEach(([time,open])=>test('Bangkok work window '+time,()=>assert.equal(C.windowOpen(time),open)));
test('batch takes exactly 20 new signals',()=>{let a=Array.from({length:43},(_,i)=>({...build(),id:'D'+i})),sent={D0:true};let batch=C.fullBatch(a,sent,'2026-09-30',14);assert.equal(batch.length,20);assert.ok(!batch.some(d=>d.id==='D0'));});
test('partial queue remains partial, no fake signals',()=>assert.equal(C.fullBatch([build()],{},'2026-09-30',14).length,1));
test('rejected and stale are excluded from digest',()=>assert.equal(C.fullBatch([{...build(),state:'REJECTED'},{...build(),published_at:'2025-01-01'}],{},'2026-09-30',14).length,0));

test('no media products, rates or meeting pitch in generated outreach',()=>{let d=build();for(const lang of ['TH','EN']){const mail=C.emails(d,ctx)[lang];assert.ok(!/PBTV|The 20|Signature Max|media solutions|20-minute|เสนอให้พิจารณา|แพ็กเกจสื่อ/.test(mail.subject+' '+mail.body));}assert.ok(C.emails(d,ctx).EN.body.includes('knowledge library'));});
test('knowledge outreach requires at least one document',()=>{let d=build();d.credentials=[];d.review_confirmed=true;assert.ok(C.validate(d,ctx).errors.some(e=>e.includes('อย่างน้อย 1')));});
test('same research topic is not sent twice',()=>{let same=[{...docs[0],topic:'TRUST'},{...docs[1],topic:'TRUST'}];assert.equal(C.credentials(build(),same).length,1);});
test('garbled extraction held for OCR',()=>assert.equal(C.describeDoc(('abc long content sample knowledge. '+String.fromCharCode(0xfffd).repeat(5)+'\n').repeat(10),'RESEARCH','Research'),null));
test('general research can support a specific industry',()=>{const general={...docs[0],tags:'GENERAL|LAUNCH',topic:'GENERAL_TRUST'};assert.equal(C.credentials({...build(),industry:'FINANCE',objective:'LAUNCH'},[general]).length,1);});
test('missing knowledge summaries prevent client draft',()=>{let local={...ctx,credentials:docs.map(c=>({...c,summary_en:''}))};assert.equal(C.validate(build(),local).ok,false);});

test('general retail news does not receive unrelated active lifestyle research',()=>{let d={...build(),industry:'RETAIL',title:'Store expansion',target:'GENERAL'},c={...docs[0],topic:'ACTIVE_LIFESTYLE',tags:'RETAIL|EXPANSION'};assert.equal(C.credentials(d,[c]).length,0);d.title='Sports store expansion';assert.equal(C.credentials(d,[c]).length,1);});
test('QSR news without delivery context does not receive delivery-app research',()=>{let d={...build(),industry:'QSR',title:'New restaurant launch',target:'GENERAL'},c={...docs[0],topic:'ON_DEMAND_JOURNEY',tags:'QSR|LAUNCH'};assert.equal(C.credentials(d,[c]).length,0);d.title='Food delivery campaign';assert.equal(C.credentials(d,[c]).length,1);});
console.log('TOTAL '+count+' core checks');


