/* In-memory Google integration checks; real OAuth/RSS/OCR/Gmail require installation. */
const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
function runtime(){const tables={},properties={INSTALLER_EMAIL:'installer@example.com',SHEET_ID:'sheet'},drafts=[],sent=[],events=[];let clock='2026-09-30T01:30:00Z',quota=100,sendFail=false,liveStamp=null,liveTrashed=false;
class Sheet{constructor(){this.data=[];}getLastRow(){return this.data.length;}getMaxRows(){return 1000;}setFrozenRows(){return this;}getRange(row,col,n,m){let self=this;return {getValues(){return Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>self.data[row+i-1]?.[col+j-1]??''));},setValues(values){values.forEach((r,i)=>{if(!self.data[row+i-1])self.data[row+i-1]=[];r.forEach((v,j)=>self.data[row+i-1][col+j-1]=typeof v==='string'&&v.startsWith("'")?v.slice(1):v);});return this;},setNumberFormat(){return this;}};}}
const ss={getId:()=> 'sheet',getSheetByName:n=>tables[n]||null,insertSheet:n=>tables[n]=new Sheet(),setSpreadsheetTimeZone:()=>{}};
class FakeDate extends Date{constructor(...args){super(...(args.length?args:[clock]));}static now(){return +new Date(clock);}}
function makeDraft(to,subject,body,options){const id='draft'+(drafts.length+1),d={id,to,subject,body,options,getId:()=>id,getMessage:()=>({getSubject:()=>subject}),send(){events.push('send');if(sendFail)throw Error('network outcome uncertain');sent.push(d);d.removed=true;return {getId:()=> 'message'+sent.length};}};drafts.push(d);return d;}
const box={console,Date:FakeDate,SpreadsheetApp:{openById:()=>ss,getActive:()=>ss,getUi:()=>({alert:()=>{}}),flush:()=>events.push('flush')},Session:{getEffectiveUser:()=>({getEmail:()=>properties.INSTALLER_EMAIL})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties[k]||null,setProperty:(k,v)=>properties[k]=v,setProperties:v=>Object.assign(properties,v),deleteProperty:k=>delete properties[k]})},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock:()=>{}})},Utilities:{formatDate:d=>new Date(+d+7*3600000).toISOString().slice(0,10),computeDigest:(a,s)=>[...crypto.createHash('sha256').update(s).digest()],DigestAlgorithm:{SHA_256:'sha256'}},ScriptApp:{getProjectTriggers:()=>[],newTrigger:handler=>({timeBased(){return this;},everyMinutes(n){events.push('trigger:'+handler+':'+n);return this;},create(){return this;}})},GmailApp:{getDrafts:()=>drafts.filter(d=>!d.removed),getDraft:id=>{let d=drafts.find(d=>d.id===id&&!d.removed);if(!d)throw Error('no draft');return d;},createDraft:makeDraft,search:()=>[]},MailApp:{getRemainingDailyQuota:()=>quota},Drive:{Files:{get:id=>({modifiedTime:liveStamp||box.rows_('Documents').find(c=>c.id===id)?.modified_at||'2026-09-30T01:00:00Z',trashed:liveTrashed,webViewLink:'https://drive.google.com/file/d/'+id+'/view'})},Permissions:{list:()=>({permissions:[{type:'anyone',role:'reader'}]})}}};
vm.createContext(box);for(const f of ['Core.gs','Seed.gs','Code.gs'])vm.runInContext(fs.readFileSync(root+'/apps-script/'+f,'utf8'),box);const fixture=JSON.parse(fs.readFileSync(root+'/data/demo.json','utf8'));box.REVENUE_SEED.accounts=fixture.accounts;box.REVENUE_SEED.credentials=fixture.credentials;box.setup();box.upsert_('Settings',{key:'news_enabled',value:false});box.upsert_('Settings',{key:'digest_enabled',value:true});box.upsert_('Settings',{key:'digest_to',value:'installer@example.com'});
let a=box.rows_('Brands')[0];a.customer_type='PROSPECT';a.contact_email='client@example.com';box.upsert_('Brands',a);
function add(n=20){for(let i=0;i<n;i++){const d=box.RevenueCore.build({id:'D'+i,account_id:a.id,title:a.brand+' เปิดตัวผลิตภัณฑ์ใหม่ รุ่น '+i,source_url:'https://example.com/news/'+i,publisher:'Test publisher',published_at:'2026-09-30'},box.context_());box.persist_(d);}}
return {box,ss,properties,drafts,sent,events,add,clock:v=>clock=v,quota:v=>quota=v,fail:v=>sendFail=v,stamp:v=>liveStamp=v,trashed:v=>liveTrashed=v};}
test('setup preserves and seeds fictional test brands, no Inventory or prices',()=>{let r=runtime();assert.equal(r.box.rows_('Brands').length,3);assert.equal(r.ss.getSheetByName('Inventory'),null);assert.equal(r.box.rows_('Documents').length,4);});
test('fictional seed brands have no invented customer type',()=>{let r=runtime();assert.equal(r.box.rows_('Brands').filter(a=>a.customer_type==='UNKNOWN').length,2);});
test('schedule uses five minute polling',()=>{let r=runtime();r.box.installSchedule();assert.ok(r.events.includes('trigger:scheduleTick:5'));});
test('cannot enable digest without recipients',()=>{let r=runtime();r.box.upsert_('Settings',{key:'digest_to',value:''});assert.throws(()=>r.box.installSchedule());});
test('disabled digest sends nothing',()=>{let r=runtime();r.add();r.box.upsert_('Settings',{key:'digest_enabled',value:false});assert.equal(r.box.sendDigest_(r.box.context_()),'PAUSED');assert.equal(r.sent.length,0);});
test('08:29 cannot send',()=>{let r=runtime();r.add();r.clock('2026-09-30T01:29:00Z');assert.equal(r.box.sendDigest_(r.box.context_()),'PAUSED');});
test('18:00 cannot send',()=>{let r=runtime();r.add();r.clock('2026-09-30T11:00:00Z');assert.equal(r.box.sendDigest_(r.box.context_()),'PAUSED');});
test('weekend poll performs no work',()=>{let r=runtime();r.clock('2026-10-03T03:00:00Z');assert.equal(r.box.scheduleTick(),undefined);assert.equal(r.drafts.length,0);});
test('19 signals wait for 20',()=>{let r=runtime();r.add(19);assert.equal(r.box.sendDigest_(r.box.context_()),'WAITING_FOR_20');assert.equal(r.sent.length,0);});
test('20 signals sent to internal recipient with sources and distinct classification',()=>{let r=runtime();r.add();assert.equal(r.box.sendDigest_(r.box.context_()),'SENT_20');assert.equal(r.sent[0].to,'installer@example.com');assert.ok(r.sent[0].options.htmlBody.includes('New Opportunity'));assert.ok(r.sent[0].options.htmlBody.includes('Test publisher'));assert.ok(r.sent[0].options.htmlBody.includes('https://example.com/news/19'));});
test('send checkpoint flushed before delivery',()=>{let r=runtime();r.add();r.box.sendDigest_(r.box.context_());assert.ok(r.events.indexOf('flush')<r.events.indexOf('send'));});
test('no resend of already delivered signals',()=>{let r=runtime();r.add();r.box.sendDigest_(r.box.context_());assert.equal(r.box.sendDigest_(r.box.context_()),'WAITING_FOR_20');assert.equal(r.sent.length,1);});
test('repeat in full 20-signal batches without inflating remainder',()=>{let r=runtime();r.add(43);assert.equal(r.box.sendDigest_(r.box.context_()),'SENT_20');assert.equal(r.box.sendDigest_(r.box.context_()),'SENT_20');assert.equal(r.box.sendDigest_(r.box.context_()),'WAITING_FOR_20');assert.equal(r.sent.length,2);});
test('quota exhaustion holds queue without marking sent',()=>{let r=runtime();r.add();r.quota(0);assert.equal(r.box.sendDigest_(r.box.context_()),'QUOTA_WAIT');assert.equal(r.box.rows_('Deliveries').length,0);r.quota(1);assert.equal(r.box.sendDigest_(r.box.context_()),'SENT_20');});
test('uncertain send blocks automatic duplicate retry',()=>{let r=runtime();r.add();r.fail(true);assert.equal(r.box.sendDigest_(r.box.context_()),'UNCERTAIN');r.fail(false);assert.equal(r.box.sendDigest_(r.box.context_()),'HELD_UNCERTAIN');assert.equal(r.drafts.length,1);});
test('digest category refreshed from current master',()=>{let r=runtime();r.add();let a=r.box.rows_('Brands')[0];a.customer_type='EXISTING';r.box.upsert_('Brands',a);r.box.sendDigest_(r.box.context_());assert.ok(r.sent[0].options.htmlBody.includes('Upsales'));assert.ok(!r.sent[0].options.htmlBody.includes('New Opportunity'));});
test('saveReview uses optimistic version and updates both languages',()=>{let r=runtime();r.add(1);r.box.saveReview('D0',1,{emails:{TH:{subject:'แก้',body:'ไทย'},EN:{subject:'Edit',body:'English'}}});assert.equal(r.box.read_('D0').version,2);assert.equal(r.box.read_('D0').emails.EN.body,'English');assert.throws(()=>r.box.saveReview('D0',1,{}));});
test('max three docs enforced server-side',()=>{let r=runtime();r.add(1);assert.throws(()=>r.box.saveReview('D0',1,{credentials:[{},{},{},{}]}));});
test('client approval creates HTML Gmail draft with no attachments and never sends',()=>{let r=runtime();r.add(1);let d=r.box.read_('D0');d.review_confirmed=true;d.links_access_confirmed=true;r.box.persist_(d);r.box.approveDraft('D0',1);assert.equal(r.drafts.length,1);assert.equal(r.sent.length,0);assert.ok(r.drafts[0].options.htmlBody.includes('News')||r.drafts[0].options.htmlBody.includes('ข่าวอ้างอิง'));assert.equal(r.drafts[0].options.attachments,undefined);assert.equal(r.box.read_('D0').state,'DRAFTED');});
test('approved draft retry is idempotent',()=>{let r=runtime();r.add(1);let d=r.box.read_('D0');d.review_confirmed=true;d.links_access_confirmed=true;r.box.persist_(d);r.box.approveDraft('D0',1);r.box.approveDraft('D0',1);assert.equal(r.drafts.length,1);});
test('live changed Drive document blocks draft even if user checked access',()=>{let r=runtime();r.add(1);const c={id:'C',status:'READY',file_name:'secret.pdf',modified_at:'2026-09-30T01:00:00Z',drive_url:'https://drive.google.com/file/d/C/view',title_th:'แนวทางสื่อ',title_en:'Media solutions',readers:'anyone'};r.box.upsert_('Documents',c);let d=r.box.read_('D0');d.credentials=[{id:'C',modified_at:c.modified_at,title_th:c.title_th,title_en:c.title_en}];d.review_confirmed=true;d.links_access_confirmed=true;r.box.persist_(d);r.stamp('2026-09-30T02:00:00Z');assert.throws(()=>r.box.approveDraft('D0',1),/เอกสาร/);assert.equal(r.drafts.length,0);});
test('reject prevents client draft',()=>{let r=runtime();r.add(1);r.box.rejectSignal('D0',1);assert.throws(()=>r.box.approveDraft('D0',2));assert.equal(r.drafts.length,0);});
test('run processes a source-backed input without price fields',()=>{let r=runtime();let a=r.box.rows_('Brands')[0];r.box.upsert_('InputsV2',{id:'I1',brand:a.brand,title:a.brand+' เปิดตัวสินค้า',source_url:'https://example.com/source',publisher:'Publisher',published_at:'2026-09-30',status:'PENDING'});let result=r.box.runAutomation();assert.equal(result.created,1);assert.equal(r.box.rows_('InputsV2')[0].status,'DONE');assert.ok(!r.box.read_('I1').lines);});

function rss(r,items){r.box.upsert_('Settings',{key:'watchlist_news_enabled',value:false});r.box.UrlFetchApp={fetch:()=>({getResponseCode:()=>200,getContentText:()=>''})};r.box.XmlService={parse:()=>({getRootElement:()=>({getChild:()=>({getChildText:()=> 'Feed',getChildren:()=>items.map(x=>({getChildText:k=>({title:x.title,link:x.url||'https://example.com/news',pubDate:x.date||'Wed, 30 Sep 2026 00:00:00 GMT'})[k]||'',getChild:k=>k==='source'?{getText:()=> 'Source Publisher'}:null}))})})})};}
test('RSS retains source and date and rejects stale/unmatched items',()=>{let r=runtime(),a=r.box.rows_('Brands')[0];rss(r,[{title:a.brand+' เปิดตัวสินค้า - Source'},{title:a.brand+' เปิดตัวสินค้า - Source',date:'Wed, 01 Jan 2025 00:00:00 GMT'},{title:'Unmapped เปิดตัวสินค้า'}]);let queue=r.box.news_(r.box.context_(),Date.now());assert.equal(queue.length,1);assert.equal(queue[0].publisher,'Source Publisher');assert.equal(queue[0].published_at,'2026-09-30');});
test('RSS syndication duplicates merge by normalized headline',()=>{let r=runtime(),a=r.box.rows_('Brands')[0];rss(r,[{title:a.brand+' เปิดตัวสินค้า - Source A'},{title:a.brand+' เปิดตัวสินค้า - Source B'}]);assert.equal(r.box.news_(r.box.context_(),Date.now()).length,1);});
test('RSS unknown brand requires a matching verified brand hint',()=>{let r=runtime();r.box.upsert_('Feeds',{id:'NEWS-TH',active:true,url:'https://example.com/rss',brand_hint:'FreshBrand',industry_hint:'RETAIL'});rss(r,[{title:'FreshBrand launch product'},{title:'Another launch product'}]);let q=r.box.news_(r.box.context_(),Date.now());assert.equal(q.length,1);assert.equal(q[0].brand,'FreshBrand');assert.equal(r.box.RevenueCore.build(q[0],r.box.context_()).category,'NEW_OPPORTUNITY');});
test('same event with different headlines on the same day is retained',()=>{let r=runtime(),a=r.box.rows_('Brands')[0];rss(r,[{title:a.brand+' เปิดตัวสินค้า X'},{title:a.brand+' เปิดตัวสินค้า Y'}]);assert.equal(r.box.news_(r.box.context_(),Date.now()).length,2);});
test('duplicate Brand IDs stop processing',()=>{let r=runtime(),a=r.box.rows_('Brands')[0];r.box.appendMany_('Brands',[a]);assert.throws(()=>r.box.context_(),/Brand ID/);});

test('Research and Outthere categories detected from actual folder names',()=>{let r=runtime();assert.equal(r.box.kind_('/Research'),'RESEARCH');assert.equal(r.box.kind_('/Outthere Monthly'),'INDUSTRY_OVERVIEW');});
test('internal digest does not include media recommendations',()=>{let r=runtime();r.add(20);r.box.sendDigest_(r.box.context_());assert.ok(!/สื่อ:|PBTV|The 20|Signature Max/.test(r.sent[0].options.htmlBody));});

test('external recipient blocked before internal digest send',()=>{let r=runtime();r.add();r.box.upsert_('Settings',{key:'digest_to',value:'customer@external.test'});assert.throws(()=>r.box.sendDigest_(r.box.context_()),/โดเมน/);assert.equal(r.sent.length,0);assert.equal(r.drafts.length,0);});
test('production readiness is read-only and exposes deployment blockers',()=>{let r=runtime(),before=r.drafts.length,report=r.box.productionStatus();assert.equal(report.ready,false);assert.ok(report.blockers.some(x=>x.includes('Brand Master')));assert.ok(report.blockers.some(x=>x.includes('credential_root')));assert.equal(r.drafts.length,before);assert.equal(r.sent.length,0);});
test('production activation refuses missing live settings',()=>{let r=runtime();assert.throws(()=>r.box.activateProduction());assert.ok(!r.events.some(x=>x.startsWith('trigger:')));});
test('production activation validates settings and creates only the poll trigger',()=>{let r=runtime();let a=r.box.rows_('Brands')[0];a.id='LIVE-A';a.brand='Live Fixture';a.customer_type='EXISTING';r.box.upsert_('Brands',a);for(const [key,value] of Object.entries({credential_root_folder_id:'fixture-folder',sales_name:'Fixture Seller',signature_th:'ผู้ขายทดสอบ Plan B Media',signature_en:'Fixture Seller, Plan B Media',news_enabled:true})){r.box.upsert_('Settings',{key,value});}assert.equal(r.box.productionStatus().ready,true);r.box.activateProduction();assert.ok(r.events.includes('trigger:scheduleTick:5'));assert.equal(r.sent.length,0);});
test('manual company Gemini import persists TH/EN and clears approval',()=>{let r=runtime();r.add(1);let d=r.box.read_('D0');let text=JSON.stringify({signal_id:d.id,version:d.version,TH:{subject:'ข้อเสนอ Insights',body:'เรียน ทีมการตลาด ครับ'},EN:{subject:'Relevant insights',body:'Dear Marketing Team,'}});let patch={emails:r.box.RevenueCore.importCompanyDraft(text,d),review_confirmed:false};r.box.saveReview(d.id,d.version,patch);assert.equal(r.box.read_(d.id).emails.EN.body,'Dear Marketing Team,');assert.equal(r.box.read_(d.id).review_confirmed,false);assert.equal(r.drafts.length,0);assert.equal(r.sent.length,0);});
test('different IDs sharing delivered headline do not resend',()=>{let r=runtime();r.add(20);r.box.sendDigest_(r.box.context_());let d=r.box.read_('D0');d.id='COPY';d.source_url='https://another.test/reprint';r.box.persist_(d);assert.equal(r.box.sendDigest_(r.box.context_()),'WAITING_FOR_20');assert.equal(r.sent.length,1);});
console.log('TOTAL '+count+' simulated integration checks');


