/* v2: only the internal 20-signal digest is sent automatically. Customer mail is a reviewed Gmail draft. */
var TABLES={
Brands:['id','brand','aliases','customer_type','industry','area','owner','contact_name','contact_email','current_media'],
MediaCatalogue:['id','name','geography','tags','role','active','source','conflict_group'],
Documents:['id','file_name','kind','folder_path','drive_url','modified_at','seen_run','status','summary_th','summary_en','title_th','title_en','tags','readers','error','topic'],
Signals:['id','state','brand','category','version','updated_at','payload'],
Feeds:['id','active','url','brand_hint','industry_hint'],
InputsV2:['id','brand','title','source_url','publisher','published_at','industry','area','objective','target','status'],
Settings:['key','value'],AuditV2:['timestamp','action','id','detail'],
Deliveries:['id','status','signal_ids','subject','draft_id','message_id','error','updated_at'],
DraftExports:['id','signal_id','version','draft_id','subject','status','error']};
function onOpen(){SpreadsheetApp.getUi().createMenu('SignalBridge').addItem('1. ติดตั้ง / อัปเกรด','setup').addItem('เปิดหน้าตรวจ Signals','openReview').addItem('ประมวลผลตอนนี้','runAutomation').addItem('ตรวจความพร้อมใช้งานจริง','showProductionStatus').addItem('เปิดใช้งานจริง จันทร์–ศุกร์ 08:30–17:59','activateProduction').addItem('หยุด Schedule','stopSchedule').addItem('ปลดคิวส่งที่ต้องตรวจสถานะ','reconcileDeliveries').addToUi();}
function setup(){var p=PropertiesService.getScriptProperties(),email=Session.getEffectiveUser().getEmail(),ss=SpreadsheetApp.getActive();if(!email)throw Error('ระบุผู้ติดตั้งไม่ได้');if(p.getProperty('INSTALLER_EMAIL')&&p.getProperty('INSTALLER_EMAIL')!==email)throw Error('ใช้บัญชีผู้ติดตั้งเดิม');p.setProperties({INSTALLER_EMAIL:email,SHEET_ID:ss.getId()});ss.setSpreadsheetTimeZone('Asia/Bangkok');
Object.keys(TABLES).forEach(function(n){var s=ss.getSheetByName(n)||ss.insertSheet(n);if(!s.getLastRow()){s.getRange(1,1,1,TABLES[n].length).setValues([TABLES[n]]);s.setFrozenRows(1);}else if(JSON.stringify(s.getRange(1,1,1,TABLES[n].length).getValues()[0])!==JSON.stringify(TABLES[n])){var current=s.getRange(1,1,1,TABLES[n].length).getValues()[0];if(n==='Documents'&&JSON.stringify(current.slice(0,-1))===JSON.stringify(TABLES[n].slice(0,-1))&&!current[current.length-1])s.getRange(1,TABLES[n].length,1,1).setValues([['topic']]);else throw Error('หัวตารางไม่ตรง: '+n);}s.getRange(2,1,Math.max(1,s.getMaxRows()-1),TABLES[n].length).setNumberFormat('@');});
if(!rows_('Brands').length){var legacy=ss.getSheetByName('Accounts'),brands=REVENUE_SEED.accounts;if(legacy&&legacy.getLastRow()>1){var values=legacy.getDataRange().getValues(),head=values.shift();brands=values.map(function(row){var a={};head.forEach(function(k,i){a[k]=row[i];});return {id:a.id,brand:a.brand,aliases:a.aliases,industry:a.industry,area:a.area,owner:a.owner,contact_email:a.contact_email,current_media:a.current_media,customer_type:'UNKNOWN'};}).filter(function(a){return a.id&&a.brand;});}appendMany_('Brands',brands);}
var initial=config_();if(!rows_('Documents').length&&REVENUE_SEED.credentials.length&&(!initial.credential_root_folder_id||initial.credential_root_folder_id===REVENUE_SEED.config.credential_root_folder_id))appendMany_('Documents',REVENUE_SEED.credentials);if(!rows_('Feeds').length)appendMany_('Feeds',REVENUE_SEED.sources);if(!rows_('Settings').length)appendMany_('Settings',Object.keys(REVENUE_SEED.config).map(function(k){return {key:k,value:REVENUE_SEED.config[k]};}));if(!config_().credential_root_folder_id)upsert_('Settings',{key:'credential_root_folder_id',value:REVENUE_SEED.config.credential_root_folder_id});deals_().filter(function(d){return d.state!=='DRAFTED'&&d.outreach_mode!=='KNOWLEDGE';}).forEach(function(d){d.outreach_mode='KNOWLEDGE';d.media=[];d.knowledge_note_th='';d.knowledge_note_en='';d.review_confirmed=false;d.version++;d.emails=RevenueCore.emails(d,context_());persist_(d);});stopOldSchedule_();audit_('SETUP','','SignalBridge 2.3 knowledge sharing installed; old sheets preserved; schedule disabled');SpreadsheetApp.getUi().alert('SignalBridge 2.3 Knowledge พร้อมตั้งค่า\nBrands: EXISTING / PROSPECT\nSettings: Brand Sheet, Drive folder, digest_to\nเปิด Schedule เมื่อพร้อม\nอีเมลลูกค้าเป็น Draft หลังอนุมัติ');}
function ss_(){return SpreadsheetApp.openById(PropertiesService.getScriptProperties().getProperty('SHEET_ID'));}
function assertOwner_(){if(Session.getEffectiveUser().getEmail()!==PropertiesService.getScriptProperties().getProperty('INSTALLER_EMAIL'))throw Error('เฉพาะผู้ติดตั้ง');}
function timestamp_(){return new Date().toISOString();}
function today_(){return Utilities.formatDate(new Date(),'Asia/Bangkok','yyyy-MM-dd');}
function cell_(v){var s=v==null?'':v instanceof Date?v.toISOString():String(v);return /^[=+\-@]/.test(s)?"'"+s:s;}
function rows_(name){var s=ss_().getSheetByName(name);if(!s)throw Error('รัน setup ก่อน');if(s.getLastRow()<2)return [];return s.getRange(2,1,s.getLastRow()-1,TABLES[name].length).getValues().map(function(r){var o={};TABLES[name].forEach(function(k,i){o[k]=r[i] instanceof Date?r[i].toISOString():r[i];});return o;}).filter(function(r){return String(r[TABLES[name][0]])!=='';});}
function appendMany_(n,data){if(!data.length)return;var s=ss_().getSheetByName(n);s.getRange(s.getLastRow()+1,1,data.length,TABLES[n].length).setValues(data.map(function(r){return TABLES[n].map(function(k){return cell_(r[k]);});}));}
function upsert_(n,r){var all=rows_(n),i=all.findIndex(function(x){return String(x[TABLES[n][0]])===String(r[TABLES[n][0]]);}),s=ss_().getSheetByName(n);s.getRange(i<0?s.getLastRow()+1:i+2,1,1,TABLES[n].length).setValues([TABLES[n].map(function(k){return cell_(r[k]);})]);}
function audit_(action,id,detail){appendMany_('AuditV2',[{timestamp:timestamp_(),action:action,id:id,detail:String(detail).slice(0,1500)}]);}
function config_(){var c={};rows_('Settings').forEach(function(r){c[r.key]=r.value;});return c;}
function accounts_(c){if(!c.brand_sheet_id){var local=rows_('Brands'),keys={};local.forEach(function(a){if(keys[a.id])throw Error('Brand ID ซ้ำ');keys[a.id]=true;});return local;}var s=SpreadsheetApp.openById(String(c.brand_sheet_id)).getSheetByName(String(c.brand_sheet_tab||'Accounts'));if(!s)throw Error('หาแท็บ Brand Master ไม่พบ');var v=s.getDataRange().getValues(),h=v.shift();['id','brand','customer_type'].forEach(function(k){if(h.indexOf(k)<0)throw Error('Brand Master ต้องมี '+k);});var ids={},out=v.map(function(r){var a={};h.forEach(function(k,i){a[k]=r[i];});return a;}).filter(function(a){return a.id&&a.brand;});out.forEach(function(a){if(ids[a.id])throw Error('Brand ID ซ้ำ');ids[a.id]=true;});return out;}
function context_(){var c=config_();return {now:today_(),config:c,accounts:accounts_(c),media:[],credentials:rows_('Documents')};}
function digest_(s){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(s)).map(function(b){return ('0'+((b+256)%256).toString(16)).slice(-2);}).join('').slice(0,24);}
function lock_(fn){var l=LockService.getScriptLock();if(!l.tryLock(1000))return {busy:true};try{return fn();}finally{l.releaseLock();}}
function deals_(){return rows_('Signals').map(function(r){return JSON.parse(r.payload);});}
function persist_(d){upsert_('Signals',{id:d.id,state:d.state,brand:d.brand,category:d.category,version:d.version,updated_at:timestamp_(),payload:JSON.stringify(d)});}
function read_(id){var d=deals_().find(function(d){return d.id===id;});if(!d)throw Error('ไม่พบ Signal');return d;}
function openReview(){assertOwner_();SpreadsheetApp.getUi().showModalDialog(HtmlService.createHtmlOutputFromFile('Review').setWidth(1250).setHeight(850),'SignalBridge — Review & customise');}
function getReviewBundle(){assertOwner_();var ctx=context_();return {context:ctx,deals:deals_().slice(-200),deliveries:rows_('Deliveries').slice(-20),last_run:PropertiesService.getScriptProperties().getProperty('LAST_RUN')||'',demo:false};}
function saveReview(id,version,patch){assertOwner_();return lock_(function(){var d=read_(id);if(Number(version)!==d.version)throw Error('ข้อมูลเปลี่ยนแล้ว รีเฟรชก่อน');if(d.state==='DRAFTED')throw Error('สร้าง Draft แล้ว แก้ต่อใน Gmail หรือสร้าง Signal revision ใหม่');['industry','area','objective','target','media','credentials','email_to','language','outreach_mode','knowledge_note_th','knowledge_note_en','emails','review_confirmed','links_access_confirmed'].forEach(function(k){if(Object.prototype.hasOwnProperty.call(patch,k))d[k]=patch[k];});var ctx=context_();d.category=RevenueCore.classify(ctx.accounts.find(function(a){return a.id===d.account_id;}));if(!Array.isArray(d.credentials)||d.credentials.length>3)throw Error('เอกสารไม่เกิน 3 รายการ');d.media=[];d.outreach_mode='KNOWLEDGE';if(!d.emails||!d.emails.TH||!d.emails.EN)throw Error('ต้องมีอีเมล TH / EN');d.state='REVIEW';d.version++;persist_(d);audit_('EDIT',id,'v'+d.version);return getReviewBundle();});}
function liveDocs_(d,ctx){d.credentials.forEach(function(s){var c=ctx.credentials.find(function(c){return c.id===s.id;});if(!c)return;try{var f=Drive.Files.get(c.id,{fields:'id,modifiedTime,trashed,webViewLink',supportsAllDrives:true});if(f.trashed||f.modifiedTime!==c.modified_at)c.status='STALE';c.readers=permissions_(c.id);if(f.webViewLink)c.drive_url=f.webViewLink;}catch(e){c.status='INACCESSIBLE';}});}
function approveDraft(id,version){assertOwner_();return lock_(function(){var d=read_(id),ctx=context_();if(d.version!==Number(version))throw Error('ข้อมูลเปลี่ยนแล้ว');if(d.state==='REJECTED')throw Error('ต้องแก้และตรวจใหม่');liveDocs_(d,ctx);var check=RevenueCore.validate(d,ctx);if(!check.ok)throw Error(check.errors.join('\n'));var key=id+'-v'+d.version,record=rows_('DraftExports').find(function(r){return r.id===key;}),out=RevenueCore.emailOutput(d,ctx),subject=out.subject+' [RA:'+key+']';if(record&&record.status==='DONE')return {draft_id:record.draft_id,bundle:getReviewBundle()};var matches=GmailApp.getDrafts().filter(function(x){return x.getMessage().getSubject()===subject;});if(matches.length>1)throw Error('พบ Draft ซ้ำ ต้องตรวจใน Gmail');var draft=matches[0]||GmailApp.createDraft(d.email_to,subject,out.text,{htmlBody:out.html});upsert_('DraftExports',{id:key,signal_id:id,version:d.version,draft_id:draft.getId(),subject:subject,status:'DONE',error:''});d.state='DRAFTED';persist_(d);audit_('APPROVED_DRAFT',id,'language '+d.language+'; no attachments; not sent');return {draft_id:draft.getId(),bundle:getReviewBundle()};});}
function rejectSignal(id,version){assertOwner_();return lock_(function(){var d=read_(id);if(d.version!==Number(version)||d.state==='DRAFTED')throw Error('Signal เปลี่ยนหรือสร้าง Draft แล้ว');d.state='REJECTED';d.version++;persist_(d);return getReviewBundle();});}
function stopOldSchedule_(){ScriptApp.getProjectTriggers().filter(function(t){return ['runAutomation','scheduleTick'].indexOf(t.getHandlerFunction())>=0;}).forEach(function(t){ScriptApp.deleteTrigger(t);});}
function installSchedule(){assertOwner_();var c=config_();if(!RevenueCore.yes(c.digest_enabled)||!String(c.digest_to||'').trim())throw Error('ตั้ง digest_enabled=TRUE และ digest_to ก่อน');var recipients=internalRecipients_(c.digest_to);if(!recipients.length)throw Error('ผู้รับไม่ถูกต้อง');stopOldSchedule_();ScriptApp.newTrigger('scheduleTick').timeBased().everyMinutes(5).create();audit_('SCHEDULE_ON','','Asia/Bangkok; weekday 08:30 <= time < 18:00; full 20 only; approximate polling');}
function stopSchedule(){assertOwner_();stopOldSchedule_();audit_('SCHEDULE_OFF','','Stopped');}
function scheduleTick(){assertOwner_();if(!RevenueCore.windowOpen(new Date()))return;return runAutomation();}
function runAutomation(){assertOwner_();return lock_(function(){var start=Date.now(),p=PropertiesService.getScriptProperties(),ctx=context_(),c=ctx.config,made=0,known={};deals_().forEach(function(d){known[d.id]=true;});if(p.getProperty('DOC_SCAN')||Date.now()-Number(p.getProperty('DOC_SCAN_AT')||0)>=Number(c.credential_refresh_minutes||60)*60000){try{indexDocuments_(c,start);p.setProperty('DOC_SCAN_AT',String(Date.now()));ctx.credentials=rows_('Documents');}catch(e){audit_('DOCUMENT_ERROR','',e.message);}}
var queue=rows_('InputsV2').filter(function(r){return r.status!=='DONE'&&r.status!=='REJECTED';}).map(function(r){return Object.assign({},r,{input:r});});if(RevenueCore.yes(c.news_enabled)&&Date.now()-Number(p.getProperty('NEWS_AT')||0)>=Math.max(5,Number(c.news_fetch_interval_minutes||30))*60000){var discovered=news_(ctx,start);discovered.forEach(function(t){if(!known[t.id]&&!rows_('InputsV2').some(function(r){return r.id===t.id;})){upsert_('InputsV2',Object.assign({},t,{status:'PENDING'}));}});queue=queue.concat(discovered.map(function(t){return Object.assign({},t,{input:Object.assign({},t,{status:'PENDING'})});}));p.setProperty('NEWS_AT',String(Date.now()));}
for(var i=0;i<queue.length&&made<Math.min(100,Number(c.max_signals_per_run||60))&&Date.now()-start<200000;i++){var t=queue[i];if(known[t.id]){if(t.input){t.input.status='DONE';upsert_('InputsV2',t.input);}continue;}try{var d=RevenueCore.build(t,ctx);persist_(d);known[d.id]=true;made++;if(t.input){t.input.status='DONE';upsert_('InputsV2',t.input);}}catch(e){audit_('SIGNAL_HELD',t.id,e.message);if(t.input){t.input.status='ERROR';upsert_('InputsV2',t.input);}}}
/* Newly read documents become eligible without overwriting any custom edits. */
deals_().filter(function(d){return d.state==='REVIEW'&&!d.review_confirmed&&!d.credentials.length&&d.version===1;}).slice(-100).forEach(function(d){var docs=RevenueCore.credentials(d,ctx.credentials);if(docs.length){d.credentials=docs;d.emails=RevenueCore.emails(d,ctx);persist_(d);}});
reconcileDeliveries_();var result=sendDigest_(ctx);p.setProperty('LAST_RUN',timestamp_());return {created:made,digest:result};});}
function news_(ctx,start){var p=PropertiesService.getScriptProperties(),feeds=rows_('Feeds').filter(function(f){return RevenueCore.yes(f.active);}),out=[],seen={};if(RevenueCore.yes(ctx.config.watchlist_news_enabled)){var cursor=Number(p.getProperty('BRAND_CURSOR')||0),n=Math.min(12,Number(ctx.config.watchlist_queries_per_run||8));for(var j=0;j<Math.min(n,ctx.accounts.length);j++){var a=ctx.accounts[(cursor+j)%ctx.accounts.length],q='"'+a.brand.replace(/"/g,'')+'" (เปิดตัว OR ขยายสาขา OR campaign OR launch OR expansion) when:14d';feeds.push({url:'https://news.google.com/rss/search?q='+encodeURIComponent(q)+'&hl=th&gl=TH&ceid=TH:th',brand_hint:a.brand,industry_hint:a.industry});}p.setProperty('BRAND_CURSOR',String((cursor+n)%Math.max(1,ctx.accounts.length)));}
if(feeds.length>20){var feedCursor=Number(p.getProperty('FEED_CURSOR')||0),rotated=[];for(var fi=0;fi<20;fi++)rotated.push(feeds[(feedCursor+fi)%feeds.length]);p.setProperty('FEED_CURSOR',String((feedCursor+20)%feeds.length));feeds=rotated;}feeds.forEach(function(feed){if(Date.now()-start>130000)return;if(!/^https:\/\//.test(feed.url))return;try{var r=UrlFetchApp.fetch(feed.url,{muteHttpExceptions:true,followRedirects:true});if(r.getResponseCode()!==200)throw Error('RSS HTTP '+r.getResponseCode());var channel=XmlService.parse(r.getContentText()).getRootElement().getChild('channel');if(!channel)throw Error('รองรับ RSS2 เท่านั้น');channel.getChildren('item').slice(0,60).forEach(function(item){var title=item.getChildText('title')||'',url=item.getChildText('link')||'',dt=new Date(item.getChildText('pubDate')||''),sig=RevenueCore.signal(title);if(!sig||!isFinite(+dt)||+dt>Date.now()+86400000||Date.now()-dt>Number(ctx.config.news_max_age_days||14)*86400000||!/^https:\/\//.test(url))return;var matches=ctx.accounts.filter(function(a){return RevenueCore.detectAccount(title,[a]);}),a=matches.length===1?matches[0]:null;if(matches.length>1)return;if(!a&&!feed.brand_hint)return;/* Unmapped brand feeds use an explicit verified brand hint, never guessed from a headline. */if(!a&&feed.brand_hint&&!RevenueCore.detectAccount(title,[{brand:feed.brand_hint}]))return;var brand=a?a.brand:feed.brand_hint,publisher=item.getChild('source'),name=publisher?publisher.getText():channel.getChildText('title')||'',day=Utilities.formatDate(dt,'Asia/Bangkok','yyyy-MM-dd'),clean=title.replace(/\s+-\s+[^-]+$/,'').trim(),id='news-'+digest_(RevenueCore.norm(brand)+'|'+RevenueCore.norm(clean));if(seen[id])return;seen[id]=true;out.push({id:id,account_id:a?a.id:'',brand:brand,industry:a?a.industry:feed.industry_hint,title:title,source_url:url,publisher:name,published_at:day});});}catch(e){audit_('RSS_ERROR','',String(feed.url).slice(0,150)+': '+e.message);}});return out;}
function kind_(path){return /case.study|กรณีศึกษา/i.test(path)?'CASE_STUDY':/research|งานวิจัย/i.test(path)?'RESEARCH':/industry|overview|ภาพรวม|outthere|monthly/i.test(path)?'INDUSTRY_OVERVIEW':'KNOWLEDGE_NOTE';}
function permissions_(id){try{return (Drive.Permissions.list(id,{fields:'permissions(type,emailAddress,domain,role)',supportsAllDrives:true}).permissions||[]).filter(function(r){return ['reader','writer','commenter','owner'].indexOf(r.role)>=0;}).map(function(r){return r.type==='anyone'?'anyone':r.type==='user'?'user:'+r.emailAddress:r.type==='domain'?'domain:'+r.domain:'';}).filter(Boolean).join('|');}catch(e){return '';}}
function indexDocuments_(c,start){if(!c.credential_root_folder_id)return;var p=PropertiesService.getScriptProperties(),root=String(c.credential_root_folder_id),state;try{state=JSON.parse(p.getProperty('DOC_SCAN')||'null');}catch(e){}if(!state||state.root!==root)state={root:root,run:timestamp_(),queue:[{id:root,path:'',token:''}]};if(state.queue.length){var q=state.queue[0],res=Drive.Files.list({q:"'"+q.id.replace(/'/g,'')+"' in parents and trashed = false",pageSize:100,pageToken:q.token||undefined,fields:'nextPageToken,files(id,name,mimeType,modifiedTime,webViewLink)',supportsAllDrives:true,includeItemsFromAllDrives:true});(res.files||[]).forEach(function(f){if(f.mimeType==='application/vnd.google-apps.folder'){if(state.queue.length<150)state.queue.push({id:f.id,path:q.path+'/'+f.name,token:''});else throw Error('โฟลเดอร์เกิน 150');return;}var old=rows_('Documents').find(function(x){return x.id===f.id;})||{},unchanged=old.modified_at===f.modifiedTime&&old.status==='READY'&&old.folder_path===q.path&&old.kind===kind_(q.path);upsert_('Documents',Object.assign({},old,{id:f.id,file_name:f.name,kind:kind_(q.path),folder_path:q.path,drive_url:f.webViewLink||'https://drive.google.com/file/d/'+f.id+'/view',modified_at:f.modifiedTime,seen_run:state.run,status:unchanged?'READY':'PENDING'}));});if(res.nextPageToken)q.token=res.nextPageToken;else state.queue.shift();}
var pending=rows_('Documents').filter(function(d){return d.status==='PENDING';}).slice(0,Math.min(8,Number(c.credentials_per_run||4)));pending.forEach(function(d){if(Date.now()-start>100000)return;try{var text=readDocumentText_(d.id),summary=RevenueCore.describeDoc(text,d.kind,d.folder_path);if(!summary)throw Error('อ่านข้อความได้ไม่เพียงพอ');Object.assign(d,summary,{status:'READY',readers:permissions_(d.id),error:''});}catch(e){d.status='ERROR';d.error=String(e.message).slice(0,500);}upsert_('Documents',d);});if(!state.queue.length){rows_('Documents').filter(function(d){return d.seen_run!==state.run;}).forEach(function(d){d.status='REMOVED';upsert_('Documents',d);});p.deleteProperty('DOC_SCAN');}else p.setProperty('DOC_SCAN',JSON.stringify(state));}
function readDocumentText_(id){var file=DriveApp.getFileById(id),mime=file.getMimeType(),temp='',text='';try{if(mime==='application/vnd.google-apps.document')return DocumentApp.openById(id).getBody().getText().slice(0,40000);if(mime==='application/vnd.google-apps.presentation')return slidesText_(id);if(mime==='text/plain')return file.getBlob().getDataAsString().slice(0,40000);if(file.getSize()>10*1024*1024)throw Error('ไฟล์เกิน 10MB: แปลงเป็น Google Docs / Slides หรือสรุปเป็นไฟล์ข้อความ');var asSlides=/presentation|powerpoint/.test(mime),asDocs=mime==='application/pdf'||/wordprocessingml|msword/.test(mime);if(!asSlides&&!asDocs)throw Error('รูปแบบไม่รองรับ: ใช้ PDF, Docs, Slides, PPTX, DOCX หรือ TXT');var result=Drive.Files.create({name:'RA-temp-'+id,mimeType:asSlides?'application/vnd.google-apps.presentation':'application/vnd.google-apps.document'},file.getBlob(),{fields:'id',ocrLanguage:'th'});temp=result.id;text=asSlides?slidesText_(temp):DocumentApp.openById(temp).getBody().getText();return text.slice(0,40000);}finally{if(temp)DriveApp.getFileById(temp).setTrashed(true);}}
function slidesText_(id){var out=[];SlidesApp.openById(id).getSlides().forEach(function(s){s.getPageElements().forEach(function(e){if(e.getPageElementType()===SlidesApp.PageElementType.SHAPE)out.push(e.asShape().getText().asString());else if(e.getPageElementType()===SlidesApp.PageElementType.TABLE){var t=e.asTable();for(var r=0;r<t.getNumRows();r++)for(var c=0;c<t.getNumColumns();c++)out.push(t.getCell(r,c).getText().asString());}});});return out.join('\n').slice(0,40000);}
function recipients_(s){var out=String(s||'').split(/[;,]/).map(function(x){return x.trim();}).filter(Boolean);if(out.length>10||out.some(function(x){return !/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(x);}))throw Error('digest_to ต้องเป็นอีเมลไม่เกิน 10 คน');return Array.from(new Set(out));}
function digestBody_(batch,ctx){var esc=RevenueCore.esc,html='<h2>SignalBridge — 20 Signals</h2><p>บริบทและ Knowledge เป็นมุมมองประกอบการหารือ อีเมลลูกค้ายังไม่ได้ส่ง</p>';['NEW_OPPORTUNITY','UPSALES','NEEDS_CLASSIFICATION'].forEach(function(cat){var list=batch.filter(function(d){return d.category===cat;});if(!list.length)return;html+='<h3>'+({NEW_OPPORTUNITY:'New Opportunity',UPSALES:'Upsales',NEEDS_CLASSIFICATION:'รอระบุประเภทลูกค้า'})[cat]+'</h3>';list.forEach(function(d){html+='<div style="border-bottom:1px solid #ddd;padding:12px 0"><b>'+esc(d.brand)+'</b> · '+esc(d.signal_type)+'<p><a href="'+esc(d.source_url)+'">'+esc(d.title)+'</a><br><small>'+esc(d.publisher)+' · '+esc(d.published_at)+'</small></p><p>บริบท Knowledge: '+esc(d.objective)+'</p>'+(d.credentials.length?'<ul>'+RevenueCore.selectedDocs(d,ctx).filter(function(c){return c.status==='READY';}).map(function(c){return '<li><a href="'+esc(c.drive_url)+'">'+esc(c.title_th)+'</a></li>';}).join('')+'</ul>':'<p>ยังไม่มี Knowledge ที่เกี่ยวข้องและอ่านได้</p>')+'<small>Signal ID: '+esc(d.id)+'</small></div>';});});return html+'<p><a href="https://docs.google.com/spreadsheets/d/'+esc(PropertiesService.getScriptProperties().getProperty('SHEET_ID'))+'/edit">เปิดหน้าตรวจใน Google Sheet → SignalBridge</a></p>';}
function sendDigest_(ctx){if(!RevenueCore.yes(ctx.config.digest_enabled)||!RevenueCore.windowOpen(new Date()))return 'PAUSED';var history=rows_('Deliveries');if(history.some(function(r){return r.status==='SENDING'||r.status==='UNCERTAIN';}))return 'HELD_UNCERTAIN';var sent={};history.filter(function(r){return r.status==='SENT';}).forEach(function(r){String(r.signal_ids).split('|').forEach(function(id){sent[id]=true;});});var batch=RevenueCore.fullBatch(deals_().map(function(d){d.category=RevenueCore.classify(ctx.accounts.find(function(a){return a.id===d.account_id;}));return d;}),sent,new Date(),ctx.config.news_max_age_days);if(batch.length<20)return 'WAITING_FOR_20';var recipients=internalRecipients_(ctx.config.digest_to);if(!recipients.length)return 'NO_RECIPIENT';if(MailApp.getRemainingDailyQuota()<recipients.length)return 'QUOTA_WAIT';/* Recheck immediately before side effect, including after slow scans. */if(!RevenueCore.windowOpen(new Date()))return 'PAUSED';var id='batch-'+digest_(batch.map(function(d){return d.id;}).join('|')),record=history.find(function(r){return r.id===id;})||{id:id,signal_ids:batch.map(function(d){return d.id;}).join('|'),subject:'SignalBridge | 20 Signals | '+today_()+' [RA-BATCH:'+id+']',draft_id:'',message_id:''};var html=digestBody_(batch,ctx);if(!record.draft_id){var found=GmailApp.getDrafts().filter(function(d){return d.getMessage().getSubject()===record.subject;});if(found.length>1)throw Error('Digest draft ซ้ำ');var draft=found[0]||GmailApp.createDraft(recipients.join(','),record.subject,'20 business signals — เปิดอีเมลแบบ HTML เพื่อดูรายการ',{htmlBody:html});record.draft_id=draft.getId();record.status='READY';record.updated_at=timestamp_();upsert_('Deliveries',record);}if(!RevenueCore.windowOpen(new Date()))return 'PAUSED';record.status='SENDING';record.updated_at=timestamp_();upsert_('Deliveries',record);SpreadsheetApp.flush();try{var msg=GmailApp.getDraft(record.draft_id).send();record.message_id=msg.getId();record.status='SENT';record.updated_at=timestamp_();upsert_('Deliveries',record);audit_('DIGEST_SENT',id,'20 signals');return 'SENT_20';}catch(e){/* No automatic resend after an ambiguous network failure. */record.status='UNCERTAIN';record.error=String(e.message).slice(0,500);upsert_('Deliveries',record);audit_('DELIVERY_UNCERTAIN',id,record.error);return 'UNCERTAIN';}}
function reconcileDeliveries_(){rows_('Deliveries').filter(function(r){return ['SENDING','UNCERTAIN'].indexOf(r.status)>=0;}).forEach(function(r){var threads=GmailApp.search('in:sent subject:"RA-BATCH:'+r.id+'"',0,10),matches=[];threads.forEach(function(t){t.getMessages().forEach(function(m){if(m.getSubject()===r.subject&&m.getFrom().indexOf(Session.getEffectiveUser().getEmail())>=0)matches.push(m);});});if(matches.length){r.status='SENT';r.message_id=matches[0].getId();r.error='';}else{try{GmailApp.getDraft(r.draft_id);r.status='READY';r.error='Draft still exists; retry next work-window tick';}catch(e){r.status='UNCERTAIN';r.error='ไม่พบ Draft หรือ Sent ที่ยืนยันได้ ตรวจใน Gmail ก่อน';}}r.updated_at=timestamp_();upsert_('Deliveries',r);});}
function reconcileDeliveries(){assertOwner_();return lock_(function(){reconcileDeliveries_();return getReviewBundle();});}

function internalRecipients_(value){var list=recipients_(value),domain=String(PropertiesService.getScriptProperties().getProperty('INSTALLER_EMAIL')||'').toLowerCase().split('@')[1];if(!domain||list.some(function(mail){return mail.toLowerCase().split('@')[1]!==domain;}))throw Error('digest_to ต้องเป็นผู้รับภายในโดเมนเดียวกับบัญชีผู้ติดตั้ง');return list;}
function productionStatus(){assertOwner_();var ctx=context_(),c=ctx.config,blockers=[],warnings=[],owner=PropertiesService.getScriptProperties().getProperty('INSTALLER_EMAIL'),recipients=[];
 if(!ctx.accounts.length||ctx.accounts.every(function(a){return /^DEMO-/i.test(a.id)||/^Demo /i.test(a.brand);}))blockers.push('นำเข้า Brand Master จริงแทนข้อมูล Demo');
 var unknown=ctx.accounts.filter(function(a){return RevenueCore.classify(a)==='NEEDS_CLASSIFICATION';}).length;if(unknown)warnings.push(unknown+' แบรนด์ยังเป็น UNKNOWN และจะสร้าง customer draft ไม่ได้');
 if(!c.credential_root_folder_id)blockers.push('ตั้ง credential_root_folder_id');
 var ready=ctx.credentials.filter(function(d){return d.status==='READY';}).length;if(!ready)blockers.push('ต้องมี Knowledge ที่อ่านได้และตรวจสรุปแล้วอย่างน้อย 1 รายการ');
 if(!String(c.sales_name||'').trim()||/ผู้ดูแลบัญชี|Account Manager/i.test(c.sales_name))blockers.push('ตั้งชื่อผู้ส่งจริง');
 ['signature_th','signature_en'].forEach(function(k){if(!String(c[k]||'').trim()||/ชื่อผู้ส่ง|Sender name|Company name|ชื่อบริษัท/.test(c[k]))blockers.push('ตั้งลายเซ็น '+k+' จริง');});
 try{recipients=internalRecipients_(c.digest_to);if(!recipients.length)blockers.push('ตั้ง digest_to ภายในบริษัท');}catch(e){blockers.push(e.message);}
 if(!RevenueCore.yes(c.news_enabled))blockers.push('เปิด news_enabled เมื่อทดสอบแหล่งข่าวแล้ว');
 if(!RevenueCore.yes(c.watchlist_news_enabled)&&!rows_('Feeds').some(function(f){return RevenueCore.yes(f.active)&&/^https:\/\//.test(f.url);}))blockers.push('ตั้ง RSS ที่ใช้งานได้หรือเปิด watchlist_news_enabled');
 if(!RevenueCore.yes(c.digest_enabled))blockers.push('ตั้ง digest_enabled=TRUE เมื่อพร้อมเปิดใช้งาน');
 if(rows_('Deliveries').some(function(r){return r.status==='SENDING'||r.status==='UNCERTAIN';}))blockers.push('ตรวจและกระทบยอด Deliveries ที่ยังไม่ยืนยัน');
 var quota=MailApp.getRemainingDailyQuota();if(quota<recipients.length)warnings.push('โควตาอีเมลวันนี้ไม่พอ ระบบจะพักคิว');
 warnings.push('Trigger เริ่มส่งได้ตั้งแต่ 08:30 แต่เวลาที่ Google เรียกอาจล่าช้า');
 return {version:'2.3.0',owner:owner,ready:!blockers.length,blockers:blockers,warnings:warnings,brands:ctx.accounts.length,knowledge_ready:ready,recipients:recipients,mail_quota:quota,window:'Asia/Bangkok Mon-Fri 08:30 <= time <18:00',ai_mode:'Company Gemini via browser, operated by salesperson. No LLM API.'};
}
function showProductionStatus(){var r=productionStatus();SpreadsheetApp.getUi().alert('SignalBridge 2.3\n'+(r.ready?'พร้อมเปิด Schedule':'ยังต้องตั้งค่า')+'\n'+r.blockers.concat(r.warnings).join('\n'));return r;}
function activateProduction(){var r=productionStatus();if(!r.ready)throw Error(r.blockers.join('\n'));installSchedule();return r;}
